kind: pipeline
type: kubernetes
name: demo-2048

# 跳过验证证书，根据实际情况要或不要，github不需要
clone:
  skip_verify: true

# 选择pipeline跑在demo命名空间里
metadata:
  namespace: demo

# node选择
node_selector:
  kubernetes.io/hostname: slave-14

# 挂载本地目录
volumes:
- name: cache
  host:
    path: /data/cache


# 第一阶段：构建代码
steps:
  - name: build code
    image: registry.cn-hangzhou.aliyuncs.com/hwq-infra/maven:3.6.3
    # 在容器里执行的shell命令列表  
    commands:
    - mvn clean install -DskipTests=true
    - jar -xf target/demo-2048.war
    # 在容器里挂载目录
    volumes:
      - name: cache
        path: /root/.m2
    # 当drone分支有push动作时,运行此步骤的条件       
    when:
      event: [push]
      branch: drone

# 第二阶段: 构建镜像&推送镜像
  - name: build image & push
    image: plugins/docker     # docker插件
    settings:
      # 镜像仓库组名称
      repo: harbor.od.com/demo/demo-2048
      # 镜像仓库名称
      registry: harbor.od.com
      # 在web界面中设置的密钥        
      username:
        from_secret: harbor_username    
      password:
        from_secret: harbor_password
      # 镜像tag定义
      tags:
        - ${DRONE_BRANCH}-${DRONE_COMMIT}-${DRONE_BUILD_NUMBER}
      # 启用非ssl加密
      insecure: true
      # 构建镜像的dockerfile文件
      dockerfile: ./Dockerfiles/Dockerfile

# 第三阶段: 服务滚动更新
  - name: k8s-deploy
    # Kubernetes插件
    image: danielgormly/drone-plugin-kube:0.2.0
    settings:
      build_tag: ${DRONE_BRANCH}-${DRONE_COMMIT}-${DRONE_BUILD_NUMBER}
      # yaml模板
      template: template/demo-2048.yaml
      # apiserver地址    
      server: https://apiserver:6443
      # Kubernetes服务帐户令牌
      token:
        from_secret: k8s_token
      # K8s CA证书的Base-64编码的字符串
      ca:
        from_secret: k8s_ca    
    # 当流水线成功的时候执行
    when:
      status: success
      event: [push]